# Generated by Django 3.2.6 on 2023-06-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230606_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='almohadas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='armarios',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='bancos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='cabeceras',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='camas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='colchones',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='comodas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='escritorios',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='estufas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='mesas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='muebles_de_televisor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='refrigerador',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='sillas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='sillones',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='sofas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='tocadores',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblesinmobiliario',
            name='vitrina',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
