# Generated by Django 3.2.6 on 2023-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230607_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='estatus_arrendador',
            field=models.CharField(blank=True, default='En espera', max_length=30, null=True),
        ),
    ]
