# Generated by Django 3.2.6 on 2023-06-08 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_arrendador_estatus_arrendador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionArrendador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('validacion_ine', models.CharField(blank=True, default='En revision', max_length=30, null=True)),
                ('validacion_comprobante_domicilio', models.CharField(blank=True, default='En revision', max_length=30, null=True)),
                ('validacion_predial', models.CharField(blank=True, default='En revision', max_length=30, null=True)),
                ('validacion_escrituras', models.CharField(blank=True, default='En revision', max_length=30, null=True)),
                ('estatus_arrendadores', models.CharField(blank=True, default='En espera', max_length=30, null=True)),
                ('arrendador_validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendador_validacion', to='home.arrendador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validacion_arrendador',
            },
        ),
    ]
