# Generated by Django 3.2.6 on 2023-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_validacionarrendador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacionarrendador',
            name='validacion_comprobante_domicilio',
        ),
        migrations.RemoveField(
            model_name='validacionarrendador',
            name='validacion_ine',
        ),
        migrations.RemoveField(
            model_name='validacionarrendador',
            name='validacion_predial',
        ),
        migrations.AddField(
            model_name='validacionarrendador',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
