# Generated by Django 3.2.6 on 2023-06-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230609_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosArrendamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('renta', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_1', models.CharField(blank=True, max_length=30, null=True)),
                ('comercial', models.CharField(blank=True, max_length=30, null=True)),
                ('habitacional', models.CharField(blank=True, max_length=30, null=True)),
                ('incluido', models.CharField(blank=True, max_length=30, null=True)),
                ('no_incluido', models.CharField(blank=True, max_length=30, null=True)),
                ('giro', models.CharField(blank=True, max_length=30, null=True)),
                ('cuota_mantenimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('deposito_garantia', models.CharField(blank=True, max_length=30, null=True)),
                ('mascotas_si', models.CharField(blank=True, max_length=30, null=True)),
                ('mascotas_no', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_mascotas', models.CharField(blank=True, max_length=30, null=True)),
                ('cajon_si', models.CharField(blank=True, max_length=30, null=True)),
                ('cajon_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bodega_si', models.CharField(blank=True, max_length=30, null=True)),
                ('bodega_no', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_bodegas', models.CharField(blank=True, max_length=30, null=True)),
                ('dia', models.CharField(blank=True, max_length=30, null=True)),
                ('tiempo_contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=30, null=True)),
                ('inicio_contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('fin_contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_arrendatario_fisica', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_arrendatario_moral', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_firma_contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('hora_firma', models.TimeField(blank=True, null=True)),
                ('lugar_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquilino', to='home.inquilino')),
                ('nombre_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_arrendador', to='home.arrendador')),
                ('nombre_inmueble_a_ocupar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_inmueble_a_ocupar', to='home.inmuebles')),
            ],
            options={
                'db_table': 'datos_arrendamiento',
            },
        ),
    ]
