# Generated by Django 3.2.6 on 2023-06-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_datosarrendamiento_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='bodega_no',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='bodega_si',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='cajon_no',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='cajon_si',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='comercial',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='cuota_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='giro',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='habitacional',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='incluido',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='mascotas_no',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='mascotas_si',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='no_incluido',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='numero_bodegas',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='renta',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='tipo_arrendatario_fisica',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='tipo_arrendatario_moral',
        ),
    ]
