# Generated by Django 3.2.6 on 2023-06-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230614_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='numero_mascotas',
        ),
    ]
