# Generated by Django 3.2.6 on 2023-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_datosarrendamiento_numero_mascotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='fin_contrato',
        ),
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='inicio_contrato',
        ),
        migrations.AddField(
            model_name='datosarrendamiento',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosarrendamiento',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosarrendamiento',
            name='fecha_firma_contrato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
