# Generated by Django 3.2.6 on 2023-06-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230614_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosarrendamiento',
            name='fecha_1',
        ),
    ]
