# Generated by Django 3.2.6 on 2023-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230614_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacionarrendador',
            name='estatus_arrendadores',
        ),
        migrations.AddField(
            model_name='validacionarrendador',
            name='validacion_comprobante_domicilio',
            field=models.CharField(blank=True, default='En revision', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='validacionarrendador',
            name='validacion_ine',
            field=models.CharField(blank=True, default='En revision', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='validacionarrendador',
            name='validacion_predial',
            field=models.CharField(blank=True, default='En revision', max_length=30, null=True),
        ),
    ]
