# Generated by Django 3.2.6 on 2023-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230615_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacionarrendador',
            name='estatus_documentos',
            field=models.CharField(blank=True, default='En espera', max_length=30, null=True),
        ),
    ]
