# Generated by Django 3.2.6 on 2023-06-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_validacionarrendador_estatus_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paquete', models.CharField(blank=True, max_length=30, null=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquilino', to='home.inquilino')),
                ('nombre_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_arrendador', to='home.arrendador')),
                ('nombre_inmueble_a_ocupar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_inmueble_a_ocupar', to='home.inmuebles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
