# Generated by Django 3.2.6 on 2023-06-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_paquetes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paquetes',
            table='paquetes',
        ),
    ]
