# Generated by Django 3.2.6 on 2023-06-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_agentify_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cotizacion_arrendador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_arrendador', to='home.arrendador'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_inquilino', to='home.inquilino'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cotizacion_inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_inmueble', to='home.inmuebles'),
        ),
    ]
