# Generated by Django 3.2.6 on 2023-06-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20230620_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='agentify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentify', to='home.inquilino'),
        ),
    ]
