# Generated by Django 3.2.6 on 2023-06-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_cotizacion_agentify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cotizacion_arrendador',
            new_name='arrendador',
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cotizacion_inmueble',
            new_name='inmueble',
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cliente_inquilino',
            new_name='inquilino',
        ),
    ]
