# Generated by Django 3.2.6 on 2023-06-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20230621_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='arrendador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_arrendadores', to='home.arrendador'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_inmuebles', to='home.inmuebles'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_inquilinos', to='home.inquilino'),
        ),
    ]
